### ISSUE TITLE
Ask for contact information

### ISSUE THREAD

**Issue by bokket** [zzl200012/distributed-kv#2]
您好，很高兴看到你回关我。方不方便加个wx？

**Comment by zzl200012** [comment]
微信上加了，也叫 kutori :) ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月20日(星期四) 凌晨1:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zzl200012/distributed-kv] Ask for contact information (#2)

**Comment by bokket** [comment]
thx，close
